export const STR = {
  ar:{
    app:'MYFI', home:'الرئيسية', debts:'الدين', goals:'الأهداف',
    reports:'التقارير', archive:'الأرشيف', settings:'الإعدادات',
    balance:'الرصيد الكلي', income:'الإيرادات', expense:'المصاريف',
    monthExp:'هذا الشهر', recent:'آخر الحركات',
    addTrans:'حركة جديدة', editTrans:'تعديل الحركة',
    addDebt:'إضافة دين', addGoal:'هدف جديد',
    amount:'المبلغ', titleField:'العنوان', note:'ملاحظة', date:'التاريخ',
    incBtn:'إيراد', expBtn:'مصروف', cat:'التصنيف', save:'حفظ',
    delete:'حذف', confirmDel:'حذف نهائياً؟', yes:'نعم', no:'لا',
    debtName:'اسم الدين', goalName:'اسم الهدف',
    addPay:'سداد أو تحصيل جديد', payHist:'سجل السداد والتحصيل', totalPaid:'إجمالي المنجز',
    remaining:'متبقي', completed:'مكتمل ✓',
    noTrans:'لا توجد معاملات مسجلة بعد', noDebts:'لا يوجد دين مسجل', noGoals:'لا توجد أهداف',
    totalInc:'الإيرادات', totalExp:'المصاريف', net:'الصافي',
    darkMode:'داكن', lightMode:'فاتح', langLabel:'اللغة',
    currency:'العملة', manageCats:'إدارة التصنيفات',
    search:'ابحث...', allCats:'الكل', recurring:'تكرار شهري',
    resetData:'حذف كل البيانات', noData:'لا توجد بيانات',
    syncing:'جارٍ المزامنة...', synced:'مزامنة ✓', syncErr:'خطأ في المزامنة',
    signOut:'تسجيل الخروج', email:'البريد الإلكتروني', password:'كلمة المرور',
    signIn:'تسجيل الدخول', signUp:'إنشاء حساب',
    continueOffline:'متابعة بدون حساب',
    nameLabel:'الاسم', exportPDF:'تصدير PDF',
    months:['يناير','فبراير','مارس','أبريل','مايو','يونيو','يوليو','أغسطس','سبتمبر','أكتوبر','نوفمبر','ديسمبر'],
    notifTitle:'MYFI 🌿', notifBody:'لا تنسَ تسجيل مصاريف اليوم',
    selectCountry:'اختر دولتك', of:'من', done:'تم',
    familyRoom:'الغرفة المشتركة', createRoom:'إنشاء غرفة',
    joinRoom:'انضم لغرفة', roomCode:'كود الغرفة',
    leaveRoom:'مغادرة الغرفة', shareCode:'شارك الكود',
    noRoom:'لا توجد غرفة مشتركة', roomCreated:'تم إنشاء الغرفة ✓',
    roomJoined:'انضممت للغرفة ✓', copiedCode:'تم نسخ الكود ✓',
    roomLeft:'غادرت الغرفة',
    roomMembers:'أعضاء',
    roomCodeHint:'أدخل الكود',
    myShare:'مشاركتي هذا الشهر',
    memberIncome:'إيراداتي',
    memberExpense:'مصاريفي',
    savingsRate:'معدل الادخار', topSpend:'أكثر تصنيف إنفاقاً',
    filterTitle:'الفلاتر', filterAll:'الكل', filterInc:'إيرادات', filterExp:'مصاريف',
    dateFrom:'من', dateTo:'إلى', clearFilter:'إعادة ضبط', applyFilter:'تطبيق',
    payAmount:'مبلغ السداد أو التحصيل', selectDebt:'اختر دين عليّ أو دين لي', selectGoal:'اختر الهدف',
    archiveTitle:'الأرشيف الشهري', currentMonth:'الحالي',

    // التنقل والشاشة الرئيسية
    commitTab:'الدين والأهداف', spaceTab:'مساحة مشتركة',
    forecastTitle:'توقع نهاية الشهر', dailyAvgLine:'معدل يومي',
    transCount:'حركة', searchPlaceholder:'بحث في الحركات...',

    // إدخال جديد (4 أوضاع)
    newEntry:'إدخال جديد', expMode:'مصروف', incMode:'دخل', debtMode:'سداد أو تحصيل', goalMode:'توفير لهدف',
    payDebtAction:'تسجيل سداد', saveGoalAction:'إضافة للتوفير',
    remainingOf:'متبقي', today_:'اليوم',

    // دين/هدف جديد
    newDebt:'دين جديد', newGoal:'هدف جديد', debtTotalAmount:'إجمالي الدين', goalTargetAmount:'المبلغ المستهدف',
    startDate:'تاريخ البدء', addDebtAction:'إضافة الدين', addGoalAction:'إضافة الهدف',
    totalRemaining:'إجمالي المتبقي', paidPercent:'مسدد', noDebtsHint:'لا يوجد دين عليّ أو دين لي مسجل بعد',
    noGoalsHint:'لا توجد أهداف مسجلة بعد', addPaymentBtn:'سداد أو تحصيل جديد', addSavingBtn:'إضافة ادخار',
    paymentHistory:'سجل السداد والتحصيل', savingHistory:'سجل الادخار', tapAddHint:'اختر الإضافة المناسبة للبدء',

    // التقارير
    compareMonths:'قارن أشهر محددة', tapToToggle:'اضغط للإضافة أو الإزالة', balanceTrend:'تطور الرصيد (آخر 30 يوم)',
    monthBreakdown:'توزيع مصاريف الشهر', incomeShort:'دخل', expenseShort:'مصروف', netShort:'صافي',

    // الأرشيف
    yearNetSoFar:'صافي السنة حتى الآن', topCatsSpend:'أعلى التصنيفات إنفاقاً', shareBtn:'مشاركة',

    // المساحة المشتركة (تسميات إضافية)
    addMemberHint:'إضافة عضو جديد للمساحة',

    // الإعدادات
    accountSync:'الحساب والمزامنة', appearanceLang:'المظهر واللغة', financialPrefs:'التفضيلات المالية',
    security:'الأمان', smartReminders:'التذكيرات الذكية', recordsSection:'السجلات', dataSection:'البيانات',
    syncStatus:'حالة المزامنة', connected:'متصل ✓', lastSync:'آخر مزامنة',
    darkModeToggle:'الوضع الداكن', biometricLock:'قفل بالبصمة / PIN', changeLockCode:'تغيير رمز القفل',
    debtDueReminder:'تذكير سداد دين عليّ', beforeDueBy:'قبل الموعد بـ', daysUnit:'يوم',
    dailyLogReminder:'تذكير يومي لتسجيل المصاريف', timeLabel:'الوقت',
    lowBalanceAlert:'تنبيه انخفاض الرصيد', ifBalanceBelow:'إذا قلّ الرصيد عن',
    exportBackup:'تصدير نسخة احتياطية', exportBackupHint:'ملف يحوي كل معاملاتك ودين عليّ ودين لي وأهدافك وإعداداتك، تقدر تحفظه أو تستورده لاحقاً بجهاز ثاني',
    importBackup:'استيراد نسخة احتياطية', deleteAllData:'حذف كل البيانات', deleteAllConfirm:'سيتم حذف كل البيانات نهائياً',
    appVersion:'النسخة', monthlyArchive:'الأرشيف الشهري', editProfile:'تعديل الملف الشخصي',
    newCategory:'+ تصنيف جديد', categoryNameLabel:'اسم التصنيف', chooseIcon:'اختر أيقونة', chooseColor:'اختر لوناً',

    // البصمة
    bioPrompt:'تحقق من هويتك لفتح MYFI', bioFallback:'استخدم رمز القفل', bioNotAvailable:'البصمة غير متوفرة على هذا الجهاز',
    unlockApp:'فتح التطبيق', tryAgain:'حاول مرة أخرى',

    // البداية / Onboarding
    onboardTitle1:'تحكّم بأموالك بثقة', onboardBody1:'سجّل دخلك ومصاريفك بثوانٍ وتابع رصيدك لحظة بلحظة',
    onboardTitle2:'دين عليّ ودين لي وأهدافك بمكان واحد', onboardBody2:'تابع السداد والتحصيل والتوفير لأهدافك بكل سهولة',
    next:'التالي', skip:'تخطي', getStarted:'ابدأ الآن',
    welcomeTitle:'مرحباً بك في MYFI', welcomeBody:'ابدأ رحلتك نحو الاستقرار المالي بإضافة أول معاملة لك',
    addFirstTrans:'+ إضافة معاملة',
  },
  en:{
    app:'MYFI', home:'Dashboard', debts:'Debts', goals:'Goals',
    reports:'Reports', archive:'Archive', settings:'Settings',
    balance:'Total Balance', income:'Income', expense:'Expenses',
    monthExp:'This Month', recent:'Recent transactions',
    addTrans:'New Transaction', editTrans:'Edit Transaction',
    addDebt:'Add Debt', addGoal:'New Goal',
    amount:'Amount', titleField:'Title', note:'Note', date:'Date',
    incBtn:'Income', expBtn:'Expense', cat:'Category', save:'Save',
    delete:'Delete', confirmDel:'Delete permanently?', yes:'Yes', no:'No',
    debtName:'Debt Name', goalName:'Goal Name',
    addPay:'New Payment', payHist:'Payment History', totalPaid:'Total Paid',
    remaining:'Remaining', completed:'Completed ✓',
    noTrans:'No transactions recorded yet', noDebts:'No debts', noGoals:'No goals',
    totalInc:'Income', totalExp:'Expenses', net:'Net',
    darkMode:'Dark', lightMode:'Light', langLabel:'Language',
    currency:'Currency', manageCats:'Manage Categories',
    search:'Search...', allCats:'All', recurring:'Repeat monthly',
    resetData:'Reset All Data', noData:'No data',
    syncing:'Syncing...', synced:'Synced ✓', syncErr:'Sync error',
    signOut:'Sign Out', email:'Email', password:'Password',
    signIn:'Sign In', signUp:'Create Account',
    continueOffline:'Continue Offline',
    nameLabel:'Name', exportPDF:'Export PDF',
    months:['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],
    notifTitle:'MYFI 🌿', notifBody:"Don't forget to log today's expenses",
    selectCountry:'Select your country', of:'of', done:'Done',
    familyRoom:'Shared Room', createRoom:'Create Room',
    joinRoom:'Join a Room', roomCode:'Room Code',
    leaveRoom:'Leave Room', shareCode:'Share Code',
    noRoom:'No shared room yet', roomCreated:'Room created ✓',
    roomJoined:'Joined room ✓', copiedCode:'Code copied ✓',
    roomLeft:'Left the room',
    roomMembers:'members',
    roomCodeHint:'Enter code',
    myShare:'My Share This Month',
    memberIncome:'My Income',
    memberExpense:'My Expenses',
    savingsRate:'Savings Rate', topSpend:'Top Category',
    filterTitle:'Filters', filterAll:'All', filterInc:'Income', filterExp:'Expenses',
    dateFrom:'From', dateTo:'To', clearFilter:'Reset', applyFilter:'Apply',
    payAmount:'Payment Amount', selectDebt:'Select Debt', selectGoal:'Select Goal',
    archiveTitle:'Monthly Archive', currentMonth:'Current',

    commitTab:'Debts & Goals', spaceTab:'Shared Space',
    forecastTitle:'Month Forecast', dailyAvgLine:'Daily avg',
    transCount:'transactions', searchPlaceholder:'Search transactions...',

    newEntry:'New Entry', expMode:'Expense', incMode:'Income', debtMode:'Pay Debt', goalMode:'Save for Goal',
    payDebtAction:'Pay Installment', saveGoalAction:'Add to Savings',
    remainingOf:'Remaining', today_:'Today',

    newDebt:'New Debt', newGoal:'New Goal', debtTotalAmount:'Total Amount', goalTargetAmount:'Target Amount',
    startDate:'Start Date', addDebtAction:'Add Debt', addGoalAction:'Add Goal',
    totalRemaining:'Total Remaining', paidPercent:'paid', noDebtsHint:'No debts — tap + to add your first debt',
    noGoalsHint:'No goals — tap + to add your first goal', addPaymentBtn:'+ New Payment', addSavingBtn:'+ Add Saving',
    paymentHistory:'Payment history', savingHistory:'Savings history', tapAddHint:'Choose the relevant action to begin',

    compareMonths:'Compare Months', tapToToggle:'Tap to add or remove', balanceTrend:'Balance Trend (last 30 days)',
    monthBreakdown:'Month Expense Breakdown', incomeShort:'Income', expenseShort:'Expense', netShort:'Net',

    yearNetSoFar:'Year Net So Far', topCatsSpend:'Top Spending Categories', shareBtn:'Share',

    addMemberHint:'Add a new member to the space',

    accountSync:'Account & Sync', appearanceLang:'Appearance & Language', financialPrefs:'Financial Preferences',
    security:'Security', smartReminders:'Smart Reminders', recordsSection:'Records', dataSection:'Data',
    syncStatus:'Sync Status', connected:'Connected ✓', lastSync:'Last sync',
    darkModeToggle:'Dark Mode', biometricLock:'Biometric / PIN Lock', changeLockCode:'Change Lock Code',
    debtDueReminder:'Debt Due Reminder', beforeDueBy:'Before due by', daysUnit:'days',
    dailyLogReminder:'Daily Logging Reminder', timeLabel:'Time',
    lowBalanceAlert:'Low Balance Alert', ifBalanceBelow:'If balance drops below',
    exportBackup:'Export Backup', exportBackupHint:'A file with all your transactions, debts, goals and settings — save it or import it later on another device',
    importBackup:'Import Backup', deleteAllData:'Delete All Data', deleteAllConfirm:'All data will be permanently deleted',
    appVersion:'Version', monthlyArchive:'Monthly Archive', editProfile:'Edit Profile',
    newCategory:'+ New Category', categoryNameLabel:'Category Name', chooseIcon:'Choose Icon', chooseColor:'Choose Color',

    bioPrompt:'Verify your identity to unlock MYFI', bioFallback:'Use lock code', bioNotAvailable:'Biometrics not available on this device',
    unlockApp:'Unlock', tryAgain:'Try Again',

    onboardTitle1:'Control your money with confidence', onboardBody1:'Log income and expenses in seconds and track your balance live',
    onboardTitle2:'Debts and goals in one place', onboardBody2:'Track your debt payments and goal savings with ease',
    next:'Next', skip:'Skip', getStarted:'Get Started',
    welcomeTitle:'Welcome to MYFI', welcomeBody:'Start your journey to financial stability by adding your first transaction',
    addFirstTrans:'+ Add Transaction',
  },
};
