const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(process.argv[2] || path.join(__dirname, '..'));
const read = rel => fs.readFileSync(path.join(root, rel), 'utf8');

const history = read('src/screens/HistoryScreen.js');
const ledger = read('src/lib/activeLedgerRepository.js');
const archive = read('src/lib/localArchiveRepository.js');
const performanceData = read('src/dev/performanceTestData.js');
const performanceStorage = read('src/dev/performanceTestStorage.js');
const sync = read('src/store/slices/useSyncSlice.js');
const settings = read('src/screens/SettingsScreen.js');
const legacySettings = read('src/screens/SettingsLegacyScreen.js');
const pdf = read('src/lib/pdf.js');
const constants = read('src/lib/constants.js');
const dateField = read('src/components/DateField.js');
const ledgerDatabase = read('src/lib/ledgerDatabase.js');
const financialLedger = read('src/lib/financialLedgerV7Repository.js');
const archiveScreen = read('src/screens/ArchiveScreen.js');

assert.match(history, /visible\.length === 0 && filteredFallback\.length > 0/);
assert.match(history, /ledgerRequestRef/);
assert.match(ledger, /queryV7TransactionPage/);
assert.match(ledger, /ORDER BY t\.date_iso DESC,t\.occurred_at DESC,t\.id DESC LIMIT \?/);
assert.doesNotMatch(archive, /INSERT OR REPLACE INTO cold_archive_years/);
assert.match(archive, /ON CONFLICT\(namespace, scope, year\) DO UPDATE SET/);
assert.match(performanceData, /Math\.min\([\s\S]*now\.getTime\(\)/);
assert.match(performanceStorage, /WRITE_BATCH_SIZE = 1/);
assert.match(performanceStorage, /writePerformanceOverlay/);
assert.match(performanceStorage, /addedTransactions/);
assert.match(sync, /schedulePerformanceSnapshotWrite\(demoSnapshot/);
assert.match(sync, /clearFinancialWorkspaceV7\(\{ namespace: ledgerNamespace \}\)/);
assert.match(read('src/store/slices/dataSlice.js'), /clearFinancialWorkspaceV7\(\{ namespace: ledgerNamespace \}\)/);
assert.match(read('src/screens/HomeScreen.js'), /buildFinancialSnapshot\(\{/);
assert.doesNotMatch(read('src/screens/HomeScreen.js'), /ledgerSummaryOverride|summaryOverride/);
assert.match(read('src/screens/ReportsScreen.js'), /catSpend\(periodTrans, cats\)/);
assert.doesNotMatch(read('src/screens/ReportsScreen.js'), /periodStatsOverride/);
assert.match(ledgerDatabase, /export const enqueueLedgerWrite/);
assert.match(ledger, /flushLedgerWrites/);
assert.match(financialLedger, /const enqueueWrite = enqueueLedgerWrite/);
assert.match(archive, /enqueueLedgerWrite/);
assert.doesNotMatch(ledger, /writeQueue/);
assert.match(dateField, /pickerView === 'year'/);
assert.match(dateField, /YEAR_PAGE_SIZE = 12/);
assert.match(dateField, /onPress=\{openYearPicker\}/);
assert.match(legacySettings, /monthOnly/);
assert.match(archiveScreen, /archiveSection/);
assert.match(archiveScreen, /'timeline'.*'saved'.*'manage'/s);
assert.match(archiveScreen, /eligibleYearDetails/);
assert.match(archiveScreen, /shield-checkmark-outline/);
assert.match(archiveScreen, /ListHeaderComponent=\{renderHeader\(\)\}/);
assert.doesNotMatch(archiveScreen, /ListHeaderComponent=\{renderHeader\}/);
assert.doesNotMatch(settings, /runFinancialLedgerV7DeviceHarness/);
assert.match(settings, /Save to phone/);
assert.match(legacySettings, /newWalletCurrencyQuery/);
assert.match(legacySettings, /option\.detail/);
assert.match(pdf, /PRODUCT_FILE_PREFIX/);
assert.match(pdf, /Financial_Report/);
assert.match(constants, /theme: 'dark', themeMode: 'system'/);

console.log('MYFI 2026-08-14 field regressions contract passed.');
