const fs = require('fs');
const path = require('path');
const root = path.resolve(process.argv[2] || '.');
const read = p => fs.readFileSync(path.join(root, p), 'utf8');
const repo = read('src/lib/financialLedgerV7Repository.js');
const sync = read('src/store/slices/useSyncSlice.js');
const must = (value, label) => {
  if (!value) throw new Error(`[FAIL] ${label}`);
  console.log(`[PASS] ${label}`);
};
must(repo.includes('export const FINANCIAL_SQLITE_SCHEMA_VERSION = 8;'), 'SQLite schema remains V8');
must(repo.includes('adoptUnbootstrappedCloudLedgerIdentityV8'), 'clean V2 adoption API exists');
must(repo.includes('runLedgerExclusiveTransaction(db, async (txn)'), 'identity adoption uses exclusive SQLite transaction');
must(repo.includes("reason: 'financial_v2_adoption_local_financial_state_present'"), 'financial state blocks identity adoption');
must(repo.includes("reason: 'financial_v2_adoption_transport_state_not_clean'"), 'unexpected transport state blocks identity adoption');
must(repo.includes("entity_type='workspace' AND entity_id='workspace' AND operation='upsert'"), 'only workspace pending rows may be discarded');
must(repo.includes('DELETE FROM ledger_outbox_v3 WHERE ledger_id=?'), 'old shadow outbox is removed before identity CAS');
must(repo.includes('DELETE FROM ledger_outbox_v2'), 'old pending V1 outbox is removed');
must(repo.includes('UPDATE ledger_sync_identity_v8'), 'identity rebind is explicit');
must(repo.includes("txn.getAllAsync('PRAGMA foreign_key_check')"), 'foreign key integrity is verified before commit');
must(repo.includes("status: 'adopted_pending_bootstrap'"), 'durable adoption evidence is recorded');
must(sync.includes('adoptUnbootstrappedCloudLedgerIdentityV8,'), 'sync slice imports clean adoption API');
must(sync.includes("if (source.mode === 'v2_unbootstrapped')"), 'unbootstrapped cloud path is handled');
must(sync.includes("status: 'adopted_v2_unbootstrapped'"), 'successful adoption state is explicit');
must(sync.includes('requireV2: true'), 'clean adoption requires V2 activation');
must(sync.includes('if (cloudRecovery?.requireV2)'), 'V1 fallback is forbidden after any V2-required recovery');
must(!sync.includes('if (cloudRecovery?.recovered && cloudRecovery?.requireV2)'), 'old transient-only V1 fallback guard is removed');
must(sync.includes('[P19_FINAL_V2_ACTIVE]'), 'activation device marker exists');
must(sync.includes('[P19_FINAL_V2_SYNC_OK]'), 'steady-state V2 sync device marker exists');
must(sync.includes("reason: 'financial_v2_already_active'"), 'active V2 empty shell bypasses recovery on restart');
must(sync.indexOf("reason: 'financial_v2_already_active'") < sync.indexOf('const source = await fetchVerifiedFinancialCloudRecoverySourceV2'), 'active V2 guard runs before cloud recovery fetch');
console.log('P19 FINAL CLEAN V2 TARGETED CONTRACT: PASS');
