const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const settings = fs.readFileSync(path.join(root, 'src/screens/SettingsScreen.js'), 'utf8');
assert(settings.includes("rotation: ar ? 'تدوير الشاشة' : 'Screen rotation'"));
assert(settings.includes("autoRotate: ar ? 'تدوير تلقائي' : 'Auto rotate'"));
assert(settings.includes("choice === 'orientation'"));
assert(settings.includes("value: ['system', 'auto', 'portrait'].includes(cfg.orientationMode) ? cfg.orientationMode : 'system'"));
assert(settings.includes("{ value: 'system', label: T.useDeviceSetting, detail: isAr ?"));
assert(settings.includes("{ value: 'auto', label: T.autoRotate"));
assert(settings.includes("{ value: 'portrait', label: T.fixedPortrait"));
assert(settings.includes("const rotationValue = cfg.orientationMode === 'system'"));
assert(settings.includes("cfg.orientationMode === 'auto' ? T.autoRotate : T.fixedPortrait;"));
assert(settings.includes("const rotationNote = cfg.orientationMode === 'system' ? T.followsDevice : null;"));
assert(settings.includes("title={T.rotation} subtitle={rotationNote} value={rotationValue} onPress={() => onChoice('orientation')}"));
assert(!settings.includes("value={cfg.orientationMode === 'portrait' ? T.fixedPortrait : T.system}"));
settings.split(/\r?\n/).forEach((line,i)=>assert(!/[ \t]+$/.test(line),`SettingsScreen.js:${i+1} trailing whitespace`));
console.log('MYFI SYSTEM IDENTITY SETTINGS V4.6: PASSED');
