const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = process.argv[2] ? path.resolve(process.argv[2]) : path.resolve(__dirname, '..');
const read = rel => fs.readFileSync(path.join(root, rel), 'utf8');
const app = read('App.js');
const onboarding = read('src/screens/OnboardingScreen.js');
const settings = read('src/screens/SettingsScreen.js');
const home = read('src/screens/HomeScreen.js');
const history = read('src/screens/HistoryScreen.js');
const trackers = read('src/screens/TrackersLabScreen.js');
const reports = read('src/screens/ReportsScreen.js');

assert(app.includes('setFirstUseGuideOpen(false)'), 'Guide must not auto-open after onboarding');
assert(app.includes('onOpenGuide={() => setFirstUseGuideOpen(true)}'), 'Guide must remain replayable from Settings');
assert(onboarding.includes('privacyStrip') && !onboarding.slice(onboarding.indexOf('function TrustSlide'), onboarding.indexOf('function QuickRow')).includes('cloudVisual'), 'Third onboarding screen must focus on quick setup with one compact privacy note');
assert(settings.includes("preferencesSub: ar ? 'اللغة والمظهر' : 'Language and appearance'"), 'Preferences must be limited to language and appearance');
const pref = settings.slice(settings.indexOf('function PreferencesPage'), settings.indexOf('function FinancialPage'));
assert(!pref.includes('T.country') && !pref.includes('T.currency') && !pref.includes('T.rotation'), 'Preferences must not contain regional settings or screen rotation');
const financial = settings.slice(settings.indexOf('function FinancialPage'), settings.indexOf('function DataPage'));
assert(financial.includes("'المنطقة والعملة' : 'Region & currency'") && financial.includes("onChoice('country')") && financial.includes("onChoice('currency')"), 'Country and currency must live in Financial setup');
const rootSettings = settings.slice(settings.indexOf('function RootSettings'), settings.indexOf('function AccountPage'));
assert(rootSettings.includes('user ? (') && rootSettings.includes('T.signInTitle') && !rootSettings.includes('title={T.currency}'), 'Root Settings must avoid duplicate base currency and collapse local cloud controls');
const account = settings.slice(settings.indexOf('function AccountPage'), settings.indexOf('function DevicesPage'));
assert(account.includes('أنت تستخدم MYFI محلياً') && account.includes('T.signInTitle'), 'Local Account must show one clear local-state explanation and connect action');
assert(!settings.includes("<Text style={[s.version, { color: th.faint }]}>MYFI ·"), 'Settings must not duplicate the version footer');
assert(home.includes("attentionItems.length ? <React.Fragment") && home.includes("activeGoals.length ? <React.Fragment"), 'Home must hide empty attention and savings sections');
assert(home.includes("Number(snapshot.month.inc || 0) === 0 ? `0 ${sym}`") && home.includes("Number(snapshot.month.exp || 0) === 0 ? `0 ${sym}`"), 'Home zero metrics must not show artificial plus/minus signs');
assert(home.includes("isAr ? 'أضف أول حركة' : 'Add first entry'"), 'Home empty state must include a first-entry CTA');
assert(history.includes('hasEntries={scopedTrans.length > 0}') && history.includes('{hasEntries ? ('), 'History search/filter controls must be progressive and hidden on a truly empty ledger');
assert(trackers.includes('addTrackerAction') && trackers.includes('onNewTracker?.()'), 'Trackers must use one Add tracker action');
assert(trackers.includes('{trackers.length ? (') && trackers.includes('currentTrackers.length && summaryTiles.length'), 'Trackers filters and summary must reveal only when data exists');
assert(reports.includes('emptyReportState') && reports.includes("reportEntryCount === 0 ? { display: 'none' } : null"), 'Reports must show one no-data state instead of rows of zeros');
assert(reports.includes("reportEntryCount > 0 && setSheet('share')"), 'Report sharing must be disabled when the period has no data');
console.log('MYFI UX LOGIC REFINEMENT V2 contract: PASSED');
