-- MYFI P19-005 — Cloud Sync Protocol V2 SHADOW
-- V1 remains active. V2 is isolated by immutable ledger_id + restore_epoch.
-- Linked transaction/entity mutations share command_id and are accepted all-or-nothing.

create table if not exists public.financial_ledgers_v2 (
  ledger_id text primary key,
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  restore_epoch bigint not null default 1 check (restore_epoch > 0),
  protocol_version integer not null default 2 check (protocol_version = 2),
  minimum_supported_version integer not null default 2 check (minimum_supported_version between 1 and 2),
  status text not null default 'active' check (status in ('active','retired')),
  bootstrap_id text,
  bootstrap_manifest_hash text,
  bootstrapped_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (owner_user_id)
);

create table if not exists public.financial_commands_v2 (
  command_sequence bigint generated by default as identity primary key,
  ledger_id text not null references public.financial_ledgers_v2(ledger_id) on delete cascade,
  restore_epoch bigint not null check (restore_epoch > 0),
  command_id text not null,
  mutation_count integer not null check (mutation_count between 1 and 500),
  created_at timestamptz not null default now(),
  unique (ledger_id, restore_epoch, command_id)
);

create index if not exists financial_commands_v2_ledger_sequence_idx
  on public.financial_commands_v2(ledger_id, restore_epoch, command_sequence);

create table if not exists public.financial_entity_heads_v2 (
  ledger_id text not null references public.financial_ledgers_v2(ledger_id) on delete cascade,
  restore_epoch bigint not null check (restore_epoch > 0),
  entity_type text not null,
  entity_id text not null,
  current_revision bigint not null default 0 check (current_revision >= 0),
  last_mutation_id text,
  last_command_id text,
  updated_at timestamptz not null default now(),
  primary key (ledger_id, restore_epoch, entity_type, entity_id)
);

create table if not exists public.financial_mutations_v2 (
  server_sequence bigint generated by default as identity primary key,
  ledger_id text not null references public.financial_ledgers_v2(ledger_id) on delete cascade,
  restore_epoch bigint not null check (restore_epoch > 0),
  mutation_id text not null,
  command_id text not null,
  command_sequence bigint not null references public.financial_commands_v2(command_sequence) on delete cascade,
  device_id text not null,
  entity_type text not null,
  entity_id text not null,
  operation text not null check (operation in ('upsert','delete','void')),
  revision bigint not null check (revision > 0),
  base_revision bigint not null check (base_revision >= 0),
  protocol_version integer not null check (protocol_version = 2),
  minimum_supported_version integer not null check (minimum_supported_version between 1 and 2),
  payload_schema_version integer not null check (payload_schema_version between 1 and 1000),
  payload jsonb not null,
  created_at timestamptz not null default now(),
  check (revision = base_revision + 1),
  unique (ledger_id, restore_epoch, mutation_id),
  unique (ledger_id, restore_epoch, entity_type, entity_id, revision)
);

create index if not exists financial_mutations_v2_ledger_sequence_idx
  on public.financial_mutations_v2(ledger_id, restore_epoch, server_sequence);
create index if not exists financial_mutations_v2_command_idx
  on public.financial_mutations_v2(ledger_id, restore_epoch, command_id, server_sequence);

alter table public.financial_ledgers_v2 enable row level security;
alter table public.financial_commands_v2 enable row level security;
alter table public.financial_mutations_v2 enable row level security;
alter table public.financial_entity_heads_v2 enable row level security;

drop policy if exists financial_ledgers_v2_select_own on public.financial_ledgers_v2;
create policy financial_ledgers_v2_select_own
  on public.financial_ledgers_v2
  for select
  to authenticated
  using (owner_user_id = (select auth.uid()));

drop policy if exists financial_mutations_v2_select_own on public.financial_mutations_v2;
create policy financial_mutations_v2_select_own
  on public.financial_mutations_v2
  for select
  to authenticated
  using (
    exists (
      select 1
        from public.financial_ledgers_v2 l
       where l.ledger_id = financial_mutations_v2.ledger_id
         and l.owner_user_id = (select auth.uid())
    )
  );

revoke insert, update, delete on public.financial_ledgers_v2 from anon, authenticated;
revoke all on public.financial_commands_v2 from anon, authenticated;
revoke insert, update, delete on public.financial_mutations_v2 from anon, authenticated;
revoke all on public.financial_entity_heads_v2 from anon, authenticated;
grant select on public.financial_ledgers_v2 to authenticated;
grant select on public.financial_mutations_v2 to authenticated;

create or replace function public.register_financial_ledger_v2(
  p_ledger_id text
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_user_id uuid := auth.uid();
  v_ledger public.financial_ledgers_v2%rowtype;
begin
  if v_user_id is null then
    raise exception 'authentication_required' using errcode = '42501';
  end if;
  if coalesce(length(trim(p_ledger_id)), 0) < 16 or length(p_ledger_id) > 120 then
    raise exception 'ledger_id_invalid' using errcode = '22023';
  end if;

  select *
    into v_ledger
    from public.financial_ledgers_v2
   where owner_user_id = v_user_id
   limit 1;

  if v_ledger.ledger_id is not null then
    if v_ledger.ledger_id <> trim(p_ledger_id) then
      raise exception 'account_ledger_already_registered' using errcode = '40001';
    end if;
    return jsonb_build_object(
      'ledgerId', v_ledger.ledger_id,
      'restoreEpoch', v_ledger.restore_epoch,
      'protocolVersion', v_ledger.protocol_version,
      'minimumSupportedVersion', v_ledger.minimum_supported_version,
      'status', v_ledger.status,
    'bootstrapId', v_ledger.bootstrap_id,
    'bootstrapManifestHash', v_ledger.bootstrap_manifest_hash,
    'bootstrappedAt', v_ledger.bootstrapped_at,
      'bootstrapId', v_ledger.bootstrap_id,
      'bootstrapManifestHash', v_ledger.bootstrap_manifest_hash,
      'bootstrappedAt', v_ledger.bootstrapped_at
    );
  end if;

  insert into public.financial_ledgers_v2 (
    ledger_id, owner_user_id, restore_epoch, protocol_version,
    minimum_supported_version, status, created_at, updated_at
  ) values (
    trim(p_ledger_id), v_user_id, 1, 2, 2, 'active', now(), now()
  )
  on conflict (ledger_id) do nothing;

  select *
    into v_ledger
    from public.financial_ledgers_v2
   where ledger_id = trim(p_ledger_id)
   limit 1;

  if v_ledger.ledger_id is null or v_ledger.owner_user_id <> v_user_id then
    raise exception 'ledger_id_owned_by_another_account' using errcode = '42501';
  end if;

  return jsonb_build_object(
    'ledgerId', v_ledger.ledger_id,
    'restoreEpoch', v_ledger.restore_epoch,
    'protocolVersion', v_ledger.protocol_version,
    'minimumSupportedVersion', v_ledger.minimum_supported_version,
    'status', v_ledger.status,
    'bootstrapId', v_ledger.bootstrap_id,
    'bootstrapManifestHash', v_ledger.bootstrap_manifest_hash,
    'bootstrappedAt', v_ledger.bootstrapped_at
  );
end;
$$;

create or replace function public.get_financial_ledger_v2()
returns jsonb
language sql
security definer
set search_path = pg_catalog, public
as $$
  select coalesce(
    (
      select jsonb_build_object(
        'ledgerId', l.ledger_id,
        'restoreEpoch', l.restore_epoch,
        'protocolVersion', l.protocol_version,
        'minimumSupportedVersion', l.minimum_supported_version,
        'status', l.status,
        'bootstrapId', l.bootstrap_id,
        'bootstrapManifestHash', l.bootstrap_manifest_hash,
        'bootstrappedAt', l.bootstrapped_at
      )
        from public.financial_ledgers_v2 l
       where l.owner_user_id = auth.uid()
       limit 1
    ),
    'null'::jsonb
  );
$$;

create or replace function public.sync_financial_mutations_v2(
  p_ledger_id text,
  p_restore_epoch bigint,
  p_mutations jsonb default '[]'::jsonb,
  p_after_sequence bigint default 0,
  p_device_id text default '',
  p_limit integer default 500
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_user_id uuid := auth.uid();
  v_ledger public.financial_ledgers_v2%rowtype;
  v_command_id text;
  v_group jsonb;
  v_item jsonb;
  v_existing public.financial_mutations_v2%rowtype;
  v_existing_command public.financial_commands_v2%rowtype;
  v_head public.financial_entity_heads_v2%rowtype;
  v_command_sequence bigint;
  v_group_conflict boolean;
  v_existing_count integer;
  v_group_count integer;
  v_limit integer := greatest(1, least(coalesce(p_limit, 500), 500));
  v_count integer;
  v_accepted jsonb := '[]'::jsonb;
  v_conflicts jsonb := '[]'::jsonb;
  v_remote jsonb := '[]'::jsonb;
  v_latest bigint := greatest(0, coalesce(p_after_sequence, 0));
  v_revision bigint;
  v_base_revision bigint;
  v_protocol integer;
  v_minimum integer;
  v_payload_schema integer;
begin
  if v_user_id is null then
    raise exception 'authentication_required' using errcode = '42501';
  end if;

  select *
    into v_ledger
    from public.financial_ledgers_v2
   where ledger_id = trim(p_ledger_id)
     and owner_user_id = v_user_id
     and status = 'active'
   limit 1;

  if v_ledger.ledger_id is null then
    raise exception 'ledger_access_denied' using errcode = '42501';
  end if;
  if p_restore_epoch <> v_ledger.restore_epoch then
    raise exception 'restore_epoch_mismatch' using errcode = '40001';
  end if;
  if v_ledger.bootstrapped_at is null then
    raise exception 'financial_bootstrap_required' using errcode = '55000';
  end if;
  if jsonb_typeof(coalesce(p_mutations, '[]'::jsonb)) <> 'array' then
    raise exception 'mutations_must_be_array' using errcode = '22023';
  end if;

  v_count := jsonb_array_length(coalesce(p_mutations, '[]'::jsonb));
  if v_count > 500 then
    raise exception 'mutation_batch_too_large' using errcode = '22023';
  end if;
  if length(coalesce(p_device_id, '')) > 200 then
    raise exception 'device_id_too_long' using errcode = '22023';
  end if;

  -- Each command group is preflighted completely before any mutation in that
  -- group is inserted. Entity heads are locked in deterministic entity order.
  for v_command_id in
    select distinct item.value->>'commandId'
      from jsonb_array_elements(coalesce(p_mutations, '[]'::jsonb)) as item(value)
     order by 1
  loop
    if coalesce(v_command_id, '') = '' or length(v_command_id) > 300 then
      raise exception 'command_id_invalid' using errcode = '22023';
    end if;

    select coalesce(jsonb_agg(item.value order by
             item.value->>'entityType',
             item.value->>'entityId',
             item.value->>'mutationId'), '[]'::jsonb)
      into v_group
      from jsonb_array_elements(coalesce(p_mutations, '[]'::jsonb)) as item(value)
     where item.value->>'commandId' = v_command_id;

    v_group_count := jsonb_array_length(v_group);
    v_existing_count := 0;
    v_group_conflict := false;
    v_existing_command := null;
    select * into v_existing_command
      from public.financial_commands_v2
     where ledger_id=trim(p_ledger_id)
       and restore_epoch=p_restore_epoch
       and command_id=v_command_id
     limit 1;

    if exists (
      select 1
        from jsonb_array_elements(v_group) as item(value)
       group by item.value->>'entityType', item.value->>'entityId'
      having count(*) > 1
    ) then
      raise exception 'mutation_command_duplicate_entity' using errcode = '22023';
    end if;

    -- PRE-FLIGHT: validate, lock every entity head, then compare CAS state.
    for v_item in
      select item.value
        from jsonb_array_elements(v_group) as item(value)
       order by item.value->>'entityType',
                item.value->>'entityId',
                item.value->>'mutationId'
    loop
      v_revision := coalesce((v_item->>'revision')::bigint, 0);
      v_base_revision := coalesce((v_item->>'baseRevision')::bigint, -1);
      v_protocol := coalesce((v_item->>'protocolVersion')::integer, 0);
      v_minimum := coalesce((v_item->>'minimumSupportedVersion')::integer, 0);
      v_payload_schema := coalesce((v_item->>'payloadSchemaVersion')::integer, 0);

      if coalesce(v_item->>'mutationId', '') = ''
         or coalesce(v_item->>'commandId', '') <> v_command_id
         or coalesce(v_item->>'ledgerId', '') <> trim(p_ledger_id)
         or coalesce((v_item->>'restoreEpoch')::bigint, 0) <> p_restore_epoch
         or coalesce(v_item->>'entityType', '') = ''
         or coalesce(v_item->>'entityId', '') = ''
         or coalesce(v_item->>'operation', '') not in ('upsert', 'delete', 'void')
         or v_revision <= 0
         or v_base_revision < 0
         or v_revision <> v_base_revision + 1
         or v_protocol <> 2
         or v_minimum < 1 or v_minimum > 2
         or v_payload_schema <= 0 then
        raise exception 'mutation_v2_invalid' using errcode = '22023';
      end if;

      if length(v_item->>'mutationId') > 300
         or length(v_item->>'entityType') > 100
         or length(v_item->>'entityId') > 300
         or pg_column_size(coalesce(v_item->'payload', 'null'::jsonb)) > 1048576 then
        raise exception 'mutation_v2_limit_exceeded' using errcode = '22023';
      end if;

      insert into public.financial_entity_heads_v2 (
        ledger_id, restore_epoch, entity_type, entity_id,
        current_revision, last_mutation_id, last_command_id, updated_at
      ) values (
        trim(p_ledger_id), p_restore_epoch,
        v_item->>'entityType', v_item->>'entityId',
        0, null, null, now()
      )
      on conflict (ledger_id, restore_epoch, entity_type, entity_id) do nothing;

      select *
        into v_head
        from public.financial_entity_heads_v2
       where ledger_id = trim(p_ledger_id)
         and restore_epoch = p_restore_epoch
         and entity_type = v_item->>'entityType'
         and entity_id = v_item->>'entityId'
       for update;

      -- Re-read after the entity lock. This makes simultaneous exact retries
      -- deterministic: the losing request observes the winner after waiting.
      v_existing := null;
      select *
        into v_existing
        from public.financial_mutations_v2
       where ledger_id = trim(p_ledger_id)
         and restore_epoch = p_restore_epoch
         and mutation_id = v_item->>'mutationId'
       limit 1;

      if v_existing.mutation_id is not null then
        if v_existing.command_id is distinct from v_command_id
           or v_existing.entity_type is distinct from (v_item->>'entityType')
           or v_existing.entity_id is distinct from (v_item->>'entityId')
           or v_existing.operation is distinct from (v_item->>'operation')
           or v_existing.revision is distinct from v_revision
           or v_existing.base_revision is distinct from v_base_revision
           or v_existing.protocol_version is distinct from v_protocol
           or v_existing.minimum_supported_version is distinct from v_minimum
           or v_existing.payload_schema_version is distinct from v_payload_schema
           or v_existing.payload is distinct from coalesce(v_item->'payload', 'null'::jsonb) then
          v_group_conflict := true;
          v_conflicts := v_conflicts || jsonb_build_array(jsonb_build_object(
            'commandId', v_command_id,
            'mutationId', v_item->>'mutationId',
            'entityType', v_item->>'entityType',
            'entityId', v_item->>'entityId',
            'reason', 'mutation_id_conflict',
            'currentRevision', v_head.current_revision
          ));
        else
          v_existing_count := v_existing_count + 1;
        end if;
        continue;
      end if;

      if v_head.current_revision <> v_base_revision then
        v_group_conflict := true;
        v_conflicts := v_conflicts || jsonb_build_array(jsonb_build_object(
          'commandId', v_command_id,
          'mutationId', v_item->>'mutationId',
          'entityType', v_item->>'entityType',
          'entityId', v_item->>'entityId',
          'reason', 'base_revision_mismatch',
          'currentRevision', v_head.current_revision,
          'requestedBaseRevision', v_base_revision
        ));
      end if;
    end loop;

    if v_group_conflict then
      continue;
    end if;

    if v_existing_command.command_id is not null
       and v_existing_count <> v_group_count then
      v_conflicts := v_conflicts || jsonb_build_array(jsonb_build_object(
        'commandId',v_command_id,
        'reason','command_id_conflict'
      ));
      continue;
    end if;

    if v_existing_count > 0 and v_existing_count <> v_group_count then
      v_conflicts := v_conflicts || jsonb_build_array(jsonb_build_object(
        'commandId', v_command_id,
        'reason', 'partial_command_replay'
      ));
      continue;
    end if;

    if v_existing_count = v_group_count then
      if v_existing_command.command_id is null
         or v_existing_command.mutation_count <> v_group_count then
        v_conflicts := v_conflicts || jsonb_build_array(jsonb_build_object(
          'commandId',v_command_id,
          'reason','command_metadata_missing_or_conflicting'
        ));
        continue;
      end if;
      select v_accepted || coalesce(jsonb_agg(item.value->>'mutationId'), '[]'::jsonb)
        into v_accepted
        from jsonb_array_elements(v_group) as item(value);
      continue;
    end if;

    -- COMMIT GROUP: all CAS checks passed, so allocate one immutable command
    -- sequence and commit every mutation/head transition atomically.
    v_command_sequence := null;
    insert into public.financial_commands_v2(
      ledger_id,restore_epoch,command_id,mutation_count,created_at
    ) values (
      trim(p_ledger_id),p_restore_epoch,v_command_id,v_group_count,now()
    )
    on conflict (ledger_id,restore_epoch,command_id) do nothing
    returning command_sequence into v_command_sequence;

    if v_command_sequence is null then
      select * into v_existing_command
        from public.financial_commands_v2
       where ledger_id=trim(p_ledger_id)
         and restore_epoch=p_restore_epoch
         and command_id=v_command_id
       limit 1;
      v_conflicts := v_conflicts || jsonb_build_array(jsonb_build_object(
        'commandId',v_command_id,
        'reason','command_id_conflict',
        'existingMutationCount',v_existing_command.mutation_count
      ));
      continue;
    end if;
    for v_item in
      select item.value
        from jsonb_array_elements(v_group) as item(value)
       order by item.value->>'entityType',
                item.value->>'entityId',
                item.value->>'mutationId'
    loop
      v_revision := (v_item->>'revision')::bigint;
      v_base_revision := (v_item->>'baseRevision')::bigint;

      insert into public.financial_mutations_v2 (
        ledger_id, restore_epoch, mutation_id, command_id, command_sequence, device_id,
        entity_type, entity_id, operation, revision, base_revision,
        protocol_version, minimum_supported_version, payload_schema_version,
        payload, created_at
      ) values (
        trim(p_ledger_id), p_restore_epoch,
        v_item->>'mutationId', v_command_id, v_command_sequence,
        coalesce(nullif(p_device_id, ''), 'unknown-device'),
        v_item->>'entityType', v_item->>'entityId', v_item->>'operation',
        v_revision, v_base_revision,
        (v_item->>'protocolVersion')::integer,
        (v_item->>'minimumSupportedVersion')::integer,
        (v_item->>'payloadSchemaVersion')::integer,
        coalesce(v_item->'payload', 'null'::jsonb),
        coalesce((v_item->>'createdAt')::timestamptz, now())
      );

      update public.financial_entity_heads_v2
         set current_revision = v_revision,
             last_mutation_id = v_item->>'mutationId',
             last_command_id = v_command_id,
             updated_at = now()
       where ledger_id = trim(p_ledger_id)
         and restore_epoch = p_restore_epoch
         and entity_type = v_item->>'entityType'
         and entity_id = v_item->>'entityId';

      v_accepted := v_accepted || jsonb_build_array(v_item->>'mutationId');
    end loop;
  end loop;

  with command_candidates as (
    select c.command_sequence,c.command_id,c.mutation_count,
           sum(c.mutation_count) over (order by c.command_sequence) as cumulative_mutations,
           row_number() over (order by c.command_sequence) as command_rank
      from public.financial_commands_v2 c
     where c.ledger_id=trim(p_ledger_id)
       and c.restore_epoch=p_restore_epoch
       and c.command_sequence>greatest(0,coalesce(p_after_sequence,0))
  ),
  selected_commands as (
    select command_sequence,command_id
      from command_candidates
     where cumulative_mutations<=v_limit
        or command_rank=1
  ),
  selected_rows as (
    select m.*,cmd.mutation_count as command_mutation_count
      from public.financial_mutations_v2 m
      join selected_commands c on c.command_sequence=m.command_sequence
      join public.financial_commands_v2 cmd on cmd.command_sequence=m.command_sequence
     where m.ledger_id=trim(p_ledger_id)
       and m.restore_epoch=p_restore_epoch
     order by m.command_sequence,m.server_sequence
  )
  select coalesce(jsonb_agg(jsonb_build_object(
           'serverSequence',m.server_sequence,
           'commandSequence',m.command_sequence,
           'commandMutationCount',m.command_mutation_count,
           'ledgerId',m.ledger_id,
           'restoreEpoch',m.restore_epoch,
           'mutationId',m.mutation_id,
           'commandId',m.command_id,
           'deviceId',m.device_id,
           'entityType',m.entity_type,
           'entityId',m.entity_id,
           'operation',m.operation,
           'revision',m.revision,
           'baseRevision',m.base_revision,
           'protocolVersion',m.protocol_version,
           'minimumSupportedVersion',m.minimum_supported_version,
           'payloadSchemaVersion',m.payload_schema_version,
           'payload',m.payload,
           'createdAt',m.created_at
         ) order by m.command_sequence,m.server_sequence),'[]'::jsonb),
         coalesce(max(m.command_sequence),v_latest)
    into v_remote,v_latest
    from selected_rows m;

  return jsonb_build_object(
    'acceptedMutationIds', v_accepted,
    'conflicts', v_conflicts,
    'remoteMutations', v_remote,
    'latestSequence', v_latest,
    'hasMore', exists (
      select 1
        from public.financial_commands_v2
       where ledger_id=trim(p_ledger_id)
         and restore_epoch=p_restore_epoch
         and command_sequence>v_latest
    ),
    'ledgerId', trim(p_ledger_id),
    'restoreEpoch', p_restore_epoch,
    'protocolVersion', 2
  );
end;
$$;

revoke all on function public.register_financial_ledger_v2(text) from public, anon;
revoke all on function public.get_financial_ledger_v2() from public, anon;
revoke all on function public.sync_financial_mutations_v2(text,bigint,jsonb,bigint,text,integer) from public, anon;

grant execute on function public.register_financial_ledger_v2(text) to authenticated;
grant execute on function public.get_financial_ledger_v2() to authenticated;
grant execute on function public.sync_financial_mutations_v2(text,bigint,jsonb,bigint,text,integer) to authenticated;
