-- MYFI P19-008 — Restore Epoch V2 handshake.
-- Old epoch mutations remain immutable audit history. The active ledger epoch
-- advances atomically, so clients cannot pull/replay a superseded epoch.

create table if not exists public.financial_restore_events_v2 (
  event_id bigint generated by default as identity primary key,
  ledger_id text not null references public.financial_ledgers_v2(ledger_id) on delete cascade,
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  from_epoch bigint not null check (from_epoch > 0),
  to_epoch bigint not null check (to_epoch = from_epoch + 1),
  reason text not null check (reason in ('backup_restore','delete_local_data','controlled_recovery')),
  device_id text not null,
  created_at timestamptz not null default now(),
  unique (ledger_id, to_epoch)
);

alter table public.financial_restore_events_v2 enable row level security;

drop policy if exists financial_restore_events_v2_select_own on public.financial_restore_events_v2;
create policy financial_restore_events_v2_select_own
  on public.financial_restore_events_v2
  for select
  to authenticated
  using (owner_user_id = (select auth.uid()));

revoke insert, update, delete on public.financial_restore_events_v2 from anon, authenticated;
grant select on public.financial_restore_events_v2 to authenticated;

create or replace function public.advance_financial_restore_epoch_v2(
  p_ledger_id text,
  p_expected_epoch bigint,
  p_new_epoch bigint,
  p_reason text,
  p_device_id text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_user_id uuid := auth.uid();
  v_ledger public.financial_ledgers_v2%rowtype;
  v_event public.financial_restore_events_v2%rowtype;
begin
  if v_user_id is null then
    raise exception 'authentication_required' using errcode = '42501';
  end if;
  if p_expected_epoch <= 0
     or p_new_epoch <> p_expected_epoch + 1
     or p_reason not in ('backup_restore','delete_local_data','controlled_recovery')
     or length(coalesce(p_device_id,'')) > 200 then
    raise exception 'restore_epoch_request_invalid' using errcode = '22023';
  end if;

  select *
    into v_ledger
    from public.financial_ledgers_v2
   where ledger_id = trim(p_ledger_id)
     and owner_user_id = v_user_id
     and status = 'active'
   for update;

  if v_ledger.ledger_id is null then
    raise exception 'ledger_access_denied' using errcode = '42501';
  end if;

  -- Crash/retry idempotency: the server may already have advanced while the
  -- client still has a durable local restore intent.
  if v_ledger.restore_epoch = p_new_epoch then
    select *
      into v_event
      from public.financial_restore_events_v2
     where ledger_id = v_ledger.ledger_id
       and to_epoch = p_new_epoch
     limit 1;

    if v_event.event_id is null
       or v_event.from_epoch <> p_expected_epoch
       or v_event.reason <> p_reason then
      raise exception 'restore_epoch_idempotency_conflict' using errcode = '40001';
    end if;

    return jsonb_build_object(
      'ledgerId', v_ledger.ledger_id,
      'fromEpoch', p_expected_epoch,
      'restoreEpoch', p_new_epoch,
      'advanced', false,
      'idempotent', true,
      'protocolVersion', v_ledger.protocol_version
    );
  end if;

  if v_ledger.restore_epoch <> p_expected_epoch then
    raise exception 'restore_epoch_conflict' using errcode = '40001';
  end if;

  update public.financial_ledgers_v2
     set restore_epoch = p_new_epoch,
         updated_at = now()
   where ledger_id = v_ledger.ledger_id
     and owner_user_id = v_user_id
     and restore_epoch = p_expected_epoch;

  if not found then
    raise exception 'restore_epoch_compare_and_swap_failed' using errcode = '40001';
  end if;

  insert into public.financial_restore_events_v2 (
    ledger_id, owner_user_id, from_epoch, to_epoch, reason, device_id, created_at
  ) values (
    v_ledger.ledger_id, v_user_id, p_expected_epoch, p_new_epoch, p_reason,
    coalesce(nullif(p_device_id,''),'unknown-device'), now()
  );

  return jsonb_build_object(
    'ledgerId', v_ledger.ledger_id,
    'fromEpoch', p_expected_epoch,
    'restoreEpoch', p_new_epoch,
    'advanced', true,
    'idempotent', false,
    'protocolVersion', v_ledger.protocol_version
  );
end;
$$;

revoke all on function public.advance_financial_restore_epoch_v2(text,bigint,bigint,text,text) from public, anon;
grant execute on function public.advance_financial_restore_epoch_v2(text,bigint,bigint,text,text) to authenticated;
